### PR TITLE
add subdirectory for fire area chart

### PR DESCRIPTION
**Pull request by collnell**
This adds documentation for the #30DayChartChallenge bubble chart gif showing total area burned by wildfires as it relates to fire suppression costs, for the years  1985-2020. This is done by scraping an html table from the National Interagency Fire Center with `rvest`, plotting with `ggplot2`, and animating with `gganimate`. The final gif also had some text edits done in Photoshop.

fire_animated_annotated

This was my first endeavor with `gganimate`. It seems pretty cool, but I struggled trying to refine certain points. Specifically, `animate_time()` did not animate time as expected, where it moved the dot rather than a fade in. Using `shadow_mark()` solves this by letting points accumulate through time, but that made it additionally challenging to have `geom_text` animate simultaneously without permanence. There were also a lot of challenges with rendering the gif.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Really cool!

**Review by lindsayplatt — APPROVED** [review]
gganimate would be so much more appealing if the rendering was improved. So slow!

Love this and the dark theme with the bright fire colors 🏆

**Comment by lindsayplatt** [comment]
Oh, meant to also add that I pulled the data and built the static image in < 10 seconds. So this code is ❤️

**Comment by collnell** [comment]
I love `rvest`!

**Pull request merged**
