### PR TITLE
Map templates

### PR DESCRIPTION
**Pull request by jread-usgs**
These two should be identical visually. The svg in the `svg_dom.html` was extracted from the svg built by `topojson_d3.html` (I used [SVG crowbar](https://nytimes.github.io/svg-crowbar/) to do this quickly)

This PR allows us to test the assumption that pre-processing svgs instead of building and projecting them at runtime results in a significant load-time performance improvement. I used a simple [example from blocks](https://bl.ocks.org/mbostock/2869946) and it is in v3 of d3 instead of v4 or v5. Ideally we'd be comparing a newer version of d3 which I think would be smaller and potentially faster. 

Presently, the svg_dom example takes about 30% of the time to see a map compared to the topojson_d3.html. I'd expect that could be better yet if the svg was smaller due to dropping a lot of precision carried in the svg (e.g., `608.5506065267796`; see `geo2svg --precision` argument for this). 
But I also didn't mess w/ further quantizing the json from the example, so I think this is closer to apples to apples right now other than the version of d3 being used. @lindsaycarr would it be simple to get v5 or v4 of d3 to replace the simple js script in `topojson_d3.html`?

This load time improvement isn't a silver bullet though - we have reduced the time to see a map, but we'll need to load d3 at some point to do other cool things. But this does open the door to improved progressive loading so we reduce the risk of losing users due to lack of immediate load feedback. 

I ran this using localhost and used lighthouse performance audits w/ a simulated 3G connection but for a desktop version 
image

### CODE REVIEW

**Comment by lindsaycarr** [comment]
I think there is something else going on with the way the json is projected. Using the topojson here (https://d3js.org/us-10m.v1.json) I can get v4 and v5 to work with the following code changes, but plugging in `us.json` still creates the paths, but off the screen.

## d3.v4 
blocks example: https://bl.ocks.org/mbostock/4090848
major changes: d3.geo.path --> d3.geoPath, add `.features`, datum --> data, use `.enter()` then append path
```
<svg width="960" height="600"></svg>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/topojson.v1.min.js"></script>
<script>

d3.json("https://d3js.org/us-10m.v1.json", function(error, us) {
    if (error) throw error;

    d3.select("svg")
        .selectAll("path")
        .data(topojson.feature(us, us.objects.states).features)
        .enter()
        .append("path")
            .attr("d", d3.geoPath());
});

</script>
```

## d3.v5
only difference: use promises! `d3.json(file, function(data) { ...` becomes `d3.json(file).then(function(data){...` 
```
<svg width="960" height="600"></svg>
<script src="https://d3js.org/d3.v5.min.js"></script>
<script src="https://d3js.org/topojson.v1.min.js"></script>
<script>

d3.json("https://d3js.org/us-10m.v1.json").then(function(us) {

    d3.select("svg")
        .selectAll("path")
        .data(topojson.feature(us, us.objects.states).features)
        .enter()
        .append("path")
            .attr("d", d3.geoPath());
});

</script>
```

**Comment by jread-usgs** [comment]
do you want to PR your changes against my branch, and have your changes use v5 and `https://d3js.org/us-10m.v1.json` file? Then I can use that to update the other parts of the PR and we can compare apples to apples

**Comment by lindsaycarr** [comment]
Sure 👍

**Comment by jread-usgs** [comment]
This is updated now @lindsaycarr 

I still have issues w/ the d3 version sometimes loading blank and then needing to refresh to see the map. I am assuming this is related to promises?

**Comment by lindsaycarr** [comment]
That is my hunch. I think we still need to figure out the best way to handle promises. I wonder if writing them as this stackoverflow suggests would help with that issue? I thought they were equivalent since we are only loading the one file, but maybe that's not true. This might be the more robust way of using them. https://stackoverflow.com/questions/49534470/d3-js-v5-promise-all-replaced-d3-queue

```
var promises = [];
promises.push(d3.json("data/us.json"))
Promise.all(promises).then(function(us) {
  d3.select("svg")
      .selectAll("path")
      .data(topojson.feature(us, us.objects.states).features)
      .enter().append("path")
        .attr("d", d3.geoPath());
});
```

**Comment by jread-usgs** [comment]
for that I get `Uncaught (in promise) TypeError: Cannot read property 'states' of undefined` on this line: `.data(topojson.feature(us, us.objects.states).features)`

**Comment by lindsaycarr** [comment]
Hmmm maybe `console.log(us)` before the d3.select stuff and see what that looks like. Those values might be passed in nested one more layer since there could be more than one promise

**Pull request merged**
