### PR TITLE
Adding flood freq plot

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
This was the code used to analyze the "unusual-ness" of the MD floods that happened in 2018 and 2016. The floods happened in places that did not have long-term USGS discharge sites. 3 high-water mark measurements were taken, and those are put into long-term context with this graph.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Sounds cool! Do you have a screenshot / image you could share here?

**Comment by ldecicco-USGS** [comment]
combo3

**Comment by ldecicco-USGS** [comment]
This was just for a static graph, not using vizzy infrastructure

**Comment by ldecicco-USGS** [comment]
That is the output image...

**Comment by jread-usgs** [comment]
Please add it to the repo (instead of attaching as a comment to the PR)

**Comment by ldecicco-USGS** [comment]
OHH, got it

**Pull request merged**
