### PR TITLE
quick shifting with sf example

### PR DESCRIPTION
**Pull request by lindsayplatt**
I don't have time to do this differently right now, but wanted to share what I came up with for shifting the O-CONUS states into a CONUS view and using `sf` instead of `sp` (as we did [here](https://github.com/USGS-VIZLAB/gages-through-ages/blob/master/scripts/process/process_map.R#L80)). I'm sure we can improve upon this in the future.

The result:
image

### CODE REVIEW

**Comment by jread-usgs** [comment]
Nice work! Does it work when shifting lat/lon points too, such as gages on PR/AK/HI?

**Comment by lindsayplatt** [comment]
Have not tried that yet, but would be a pretty simple test!

**Comment by lindsayplatt** [comment]
(actually, need to do this for my purposes anyways)

**Comment by limnoliver** [comment]
Found this and modified so it allows point shifts -- will post code when I have it cleaned up! Was very happy when I was able to do this!
image

**Comment by limnoliver** [comment]
Building on Lindsay's code, the points can be shifted with this function: 

```
shift_sf_points <- function(points_sf, obj_sf, rotation_deg, scale, shift, projection, ref_sf = NULL) {
  
  stopifnot(!is.na(st_crs(obj_sf)))
  if(is.null(ref_sf)) ref_sf <- obj_sf

  # points to rotate
  points_sf_transf <- st_geometry(st_transform(points_sf, projection))

  # get the state shape into same projection, find centroid to spin on
  obj_sfg <- st_geometry(st_transform(obj_sf, projection))
  obj_centroid <- st_centroid(st_geometry(obj_sfg))

  # Rotate and scale shape and points
  obj_sf_rot_scaled <- (obj_sfg - obj_centroid) * rot(rotation_deg*pi/180) * scale + obj_centroid
  points_sf_rot_scaled <- (points_sf_transf - obj_centroid) * rot(rotation_deg*pi/180) * scale + obj_centroid

  obj_centroid_new <- st_centroid(obj_sf_rot_scaled)
  new_shift <- shift*10000+c(st_coordinates(obj_centroid)-st_coordinates(obj_centroid_new))
  
  # Shift points
  points_sf_shifted <- points_sf_rot_scaled + new_shift
  st_crs(points_sf_shifted) <- projection
  
  return(points_sf_shifted)
}
```
Tried it out with the national flow data: 
image

**Review by jread-usgs — APPROVED** [review]

**Pull request merged**
